(display "Liste simple : ")
(display (list 1 2 3 4 5))
(display "\n")
(display "Paire : ")
(display (cons 1 2))
(display "\n")
(display "Liste avec paire : ")
(display (list 1 2 (cons 2 3)))
(display "\n")
(display "Liste imbriquée : ")
(display (list 1 2 (list 3 4)))
(display "\n")
